version: "3.8"

services:
  database:
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./config/init_db.sql:/docker-entrypoint-initdb.d/init_script.sql:ro

  init_homeserver:
    command: chown 991:991 /data
    image: busybox:1.34-glibc
    restart: "no"
    volumes:
      - synapse-data:/data

  homeserver:
    command: run --config-path=/etc/synapse/homeserver.yaml
    depends_on:
      database:
        condition: service_healthy
      init_homeserver:
        condition: service_completed_successfully
    image: matrixdotorg/synapse:v1.73.0
    networks:
      - internal
      - proxy
    restart: unless-stopped
    volumes:
      - ./config/etc/synapse:/etc/synapse:ro
      - synapse-data:/data

  homeserver_admin:
    image: awesometechnologies/synapse-admin:0.8.5
    restart: unless-stopped
    networks:
      - proxy

  element-web:
    image: vectorim/element-web:v1.11.16
    restart: unless-stopped
    volumes:
      - ./config/app/config.json:/app/config.json:ro
    networks:
      - proxy

networks:
  internal:
  proxy:
    external: true

volumes:
  pg-data:
  synapse-data:
